export {default as Home } from './home'
export {default as About } from './About'
export {default as Resume } from './resume'
export {default as Contact } from './contact'
export {default as Review } from './review'